spring:
    application:
        name: webapp-service
    main:
        allow-bean-definition-overriding: true
    datasource:
        jdbcUrl: jdbc:postgresql://192.168.8.104:5432/freeland
        username: freeland
        password: freeland
        driverClassName: org.postgresql.Driver
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                temp:
                    use_jdbc_metadata_defaults: false
    thymeleaf:
        cache: false
