spring:
    datasource:
        jdbcUrl: jdbc:postgresql://192.168.8.104:5432/freeland
        username: freeland
        password: freeland
        driverClassName: org.postgresql.Driver
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                temp:
                    use_jdbc_metadata_defaults: false
                    
security:
    basic:
        enabled: false
    oauth2:
        resource:
            userInfoUri: http://localhost:8089/uaa/user
            ssoLogoutUri: http://localhost:8089/uaa/ssoLogout
            tokenInvalidateUri: http://uaa-service/uaa/invalidateToken
            
eureka:
    client:
        serviceUrl:
            defaultZone: http://ms-eureka-server:8761/eureka/    
